### ISSUE TITLE
Misleading error response if an illegal character (#) is present in the uploaded file name

### ISSUE THREAD

**Issue by sw-dev1** [OneDrive/onedrive-sdk-android#100] opened 2016-08-23 17:26 UTC
The error response is "415 Unsupported media type", without an error code.
InvalidRequest might be more appropriate, in the lack of a specific "Illegal file/item name".

Logcat extract:
                                                                                                             {
                                                                                                                "error": {
                                                                                                                   "message": "The request entity's media type 'application\/octet-stream' is not supported for this resource.",
                                                                                                                   "code": ""
                                                                                                                }
                                                                                                             }

```
                                                                                                         com.onedrive.sdk.http.OneDriveServiceException: Error code: 
                                                                                                         Error message: The request entity's media type 'application/octet-stream' is not supported for this resource.
```

**Comment by daboxu** [comment] 2016-08-31 21:39
hi @sw-dev1 , I would argue for the special character '#' here. As you add it to be a part of the file name, the finally generated url looks like:

PUT /v1.0/drive/{item}/children/file#name.extension/content

in which according to the Uri definition is a valid url and the part after '#' is a fragment. Our server regard the url equal to:

PUT /v1.0/drive/{item}/children/file

which server regards you want to do PUT to the file specified file and it expects a json object in body regards to the request.

That's why you see the Media Type error here. You will get same error by manually issuing request again OneDrive API. Hope this answer your question.

**Comment by daboxu** [comment] 2016-09-20 20:02
closing this issue as it is expected behavior

**Closed as completed by daboxu** 2016-09-20 20:02 UTC

**Comment by sw-dev1** [comment] 2016-09-28 15:53
Thank you for this clarification. Of course, this can be closed. Sorry for the hassle.
