### ISSUE TITLE
upload will fail when I upload file to OneDrive for personal 

### ISSUE THREAD

**Issue by yanbli** [OneDrive/onedrive-sdk-android#79] opened 2016-05-23 08:06 UTC
When I use microsoft account(hotmail account) to login and upload a file, the response is 

<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body {font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px0px}#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>OneDrive</title></head><body><div id='content'><div id='message'><h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p></div><div id='errorref'><span>Ref A: DF585EFBED4E48E2B34BFC2A854CA55C Ref B: AB553E4C7F4A8B9273E7805B5989367C Ref C: Thu May 19 19:34:13 2016 PST</span></div></div></body></html>

**Comment by yanbli** [comment] 2016-05-23 08:07
when I use your sample app(https://github.com/OneDrive/onedrive-explorer-android) to upload a file. It has the same issue.

**Comment by yanbli** [comment] 2016-05-24 10:38
@daboxu What's the root cause about this issue?

I found another user have the same issue
http://stackoverflow.com/questions/37360270/onedrive-put-failing-with-error-503

**Comment by skvalex** [comment] 2016-05-24 18:19
I have the same problem in my project. Got feedback from users that uploading to OneDrive doesn't work about 5 days.

**Comment by daboxu** [comment] 2016-05-25 19:56
@skvalex @yanbli the SDK 1.2.0 should have fixed the uploading issue. It is due to an update on our infrastructure at server side.

**Comment by yanbli** [comment] 2016-05-26 05:47
This issue has been fixed on latest version 1.2.0. But there is another issue,

For OneDrive personal, I can't upload the file with Chinese title. for English title file, it is fine.
For OneDrive business, all file can be uploaded.

Do you know why?

**Comment by skvalex** [comment] 2016-05-26 12:42
I can confirm the problem described above. Not only Chinese characters fail, but Cyrillic as well.
That's what I get in the log:

> Response code 400, Bad Request

The problem can be easily reproduced on https://apigee.com/OneDrive/embed/console/OneDrive
It doesn't matter if the string is urlencoded or not.

**Comment by daboxu** [comment] 2016-05-26 16:41
close this thread and move the issue for characters to #81

**Closed as completed by daboxu** 2016-05-26 16:41 UTC
